---
- hosts: all
  become: yes
  tasks:
  - name: I want to install Git on server 
    apt:
       name: git
       state: present

  - name: I want to install apache2
    apt:
       name: apache2
       state: present

  - name: I want to start the apache2 service on webserver
    apt:
       name: apache2
       state: started
